using System;
using System.Collections.Generic;
using System.Text;

namespace SONY.PTP700.SPP.PacketFactory
{ 
    public enum SppCommnadGroup : byte
    {
		CHU_SWITCH_REL = 0x20,
		CHU_SWITCH_ABS = 0x21,
		CHU_ANALOG_REL = 0x22,
		CHU_ANALOG_ABS = 0x23,
		CHU_DIAGNOSTICS_INFORMATION = 0x24,
		CHU_AUTO_SETUP_CONTROL = 0x25,
		CHU_AUTO_SETUP_INFORMATION = 0x26,
		CHU_FILE_CONTROL = 0x27,
		CHU_FILE_NAME_CONTROL = 0x28,
		CHU_SWITCH_WITH_MASK = 0x29,
		CHU_ANALOG_FOR_MASTER_SLAVE = 0x2a,
		CHU_MASTER_SETUP = 0x2b,
		CHU_SEQUENCE_CONTROL = 0x2c,
		CHU_MULTI_SWITCH = 0x30,
		CHU_MULTI_ANALOG_REL = 0x31,
		CHU_MULTI_SWITCH_STATUS_REL =  0x32,
		CHU_MULTI_ANALOG_STATUS = 0x33,
		CHU_ANALOG_TRIMMING_REL = 0x3a,
		CHU_ANALOG_TRIMMING_ABS = 0x3b,
		CHU_EXT_ANALOG_REL = 0x3c,
		CHU_EXT_ANALOG_ABS = 0x3d,

		CCU_SWITCH_REL = 0x40,
		CCU_SWITCH_ABS = 0x41,
		CCU_ANALOG_REL = 0x42,
		CCU_ANALOG_ABS = 0x43,
		CCU_DIAGNOSTICS_INFORMATION = 0x44,
		CCU_AUTO_SETUP_CONTROL = 0x45,
		CCU_AUTO_SETUP_INFORMATION = 0x46,
		CCU_FILE_CONTROL = 0x47,
		CCU_SWITCH_WITH_MASK = 0x49,
		CCU_FORMAT_CONTROL = 0x4f,
		CCU_MULTI_SWITCH = 0x50,
		CCU_MULTI_ANALOG = 0x51,
		CCU_MULTI_SWITCH_STATUS = 0x52,
		CCU_MULTI_ANALOG_STATUS = 0x53,
		CCU_ANALOG_TRIMMING_REL = 0x5a,
		CCU_ANALOG_TRIMMING_ABS = 0x5b,
		CCU_EXT_ANALOG_REL = 0x5c,
		CCU_EXT_ANALOG_ABS = 0x5d,

		CNU_SWITCH_REL = 0x60,
		CNU_SWITCH_ABS = 0x61,
		CNU_ANALOG_REL = 0x62,
		CNU_ANALOG_ABS = 0x63,
		CNU_DIAGNOSTICS_INFORMATION = 0x64,
		CNU_MULTI_SYSTEM = 0x65,
		CNU_MULTI_SWITCH = 0x68,
		CNU_MULTI_ANALOG_REL = 0x69,

		ADDRESS_SELECTOR = 0x6c,

		VCS_SWITCH_REL = 0x80,
		VCS_SWITCH_ABS = 0x81,
		VCS_ANALOG_REL = 0x82,
		VCS_ANALOG_ABS = 0x83,
		VCS_DIAGNOSTICS_INFORMATION = 0x84,
		VSC_SWITCH_WITH_MASK = 0x85,

		VCU_MULTI_SWITCH = 0x88,
		VCS_MULTI_ANALOG = 0x89,

		RCP_SWITCH_REL = 0x90,
		RCP_SWITCH_ABS = 0x91,
		
		VTR = 0xc0,
		DIGITAL_INCOM = 0xd0,
		FACTORY_SETTING = 0xfa,
		VENDER_UNIQUE_with_VENDER_CODE = 0xfc,
		VENDER_UNIQUE = 0xfd,

	};

	static class SppCommnadGroupExtensions
	{
		public static int Size(this SppCommnadGroup Value)
		{
			return -1;
		}
	}

}
